### ISSUE TITLE
Too drastic strip function on a french book 

### ISSUE THREAD

**Issue by camilodlt** [ropensci/gutenbergr#27]
Hello, 
 
I noticed that on a french book, the gutenberg_strip function removes all the content. I think it's a collection of poems, the ID of that book is 4688.

Code: 
`gutenbergr::gutenberg_download('4688', strip = T)`

the output is this : 
```
# A tibble: 1 x 2
  gutenberg_id text 
         <int> <chr>
1         4688 "" 
```

I know from the documentation that 'This is based on some formatting guesses so it may not be perfect'. I'm just raising the issue so that it is known.

**Comment by dgrtwo** [comment]
Thanks for your helpful report and thanks for using the package!

It looks like the people who constructed this text for Project Gutenberg used a different format intentionally:

> This header should be the first thing seen when anyone starts to
view the etext. Do not change or edit it without written permission.
The words are carefully chosen to provide users with the information
they need to understand what they may and may not do with the etext.
To encourage this, we have moved most of the information to the end,
rather than having it all here at the beginning.

We could try to get around it by changing `gutenberg_strip()`, but in this situation I recommend using `strip = FALSE` and removing the header (and footer) manually.
